#!/usr/bin/env python

KEYWORD_RCID = 'RCID'
KEYWORD_URL = 'URL'
KEYWORD_METHOD = 'METHOD'
KEYWORD_HEADERS = 'HEADERS'
KEYWORD_BODY = 'BODY'
KEYWORD_CONTROL = 'CONTROL'
KEYWORD_EXPECT = 'EXPECT'
KEYWORD_RC = 'RESTCASES'
KEYWORD_TC = 'TESTCASES'

CONTROL_OPT_LOOP = 'LOOP'
CONTROL_OPT_DELAY = 'DELAY'

KEYWORD_RESULT_UNKNOWN = 'UNKNOWN'
KEYWORD_RESULT_PASS = 'PASS'
KEYWORD_RESULT_FAIL = 'FAIL'
